### ISSUE TITLE
plugin is not loading

### ISSUE THREAD

**Issue by thecleaner82** [jortgies/homebridge-rademacher-blinds#1]
while trying to load the plugin after installation i got this error:

[1/12/2017, 10:37:03 PM] ====================
[1/12/2017, 10:37:03 PM] ERROR LOADING PLUGIN homebridge-rademacher-blinds:
[1/12/2017, 10:37:03 PM] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[1/12/2017, 10:37:03 PM] ====================

**Comment by jortgies** [comment]
@thecleaner82 sorry, I forgot to include the dependency into the package.json
To fix this just download the updated version (which I will release now) or just do `npm install -g request`

**Comment by thecleaner82** [comment]
great thx, its working but i can only see an control one of my blinds? I oly changed the ip to the one of the homepilot IP

**Comment by jortgies** [comment]
what kind of blinds are you using? I have no problem using the RolloTron devices.
It would be nice if you could show me the output of `http://192.168.0.1/deviceajax.do?devices=1`

**Comment by thecleaner82** [comment]
Hey. The RolloTron is fine and the one I can control. I have three additional wall mounted and a sun roof controller including weather sensors. 

Find the output below:

{ "response" : "get_visible_devices", "status" : "ok", "devices" : [{"did":10003,"name":"Couch","description":" ","initialized":1,"position":100,"productName":"Troll Comfort DuoFern","serial":"70 24 16","statusesMap":{"Position":100,"Manuellbetrieb":0},"status_changed":1484407448,"deviceGroup":2,"iconSet":{"name":"Rollladen 1","description":"Rollladen Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen1.png", "numTiles" : 5 },"k":"iconset8"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"702416_1_A","visible":true,"groups" : [ 5000, 5001 ] ,"favoredId":-1,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":2,"smoke":3,"favored":3,"trigger":2,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":2,"time":2,"dust":2,"wind":3,"states":[{"cfgKey":"setWindAuto","cfgId":111,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":1},{"cfgKey":"setRainAuto","cfgId":109,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":1}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147483414,"messages":[],"hasErrors":0,"autos":[6,2,1,0,3,4,5]},{"did":10006,"name":"Esstisch","description":"","initialized":1,"position":100,"productName":"Troll Comfort DuoFern","serial":"70 25 18","statusesMap":{"Position":100,"Manuellbetrieb":0},"status_changed":1484408832,"deviceGroup":2,"iconSet":{"name":"Rollladen 1","description":"Rollladen Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen1.png", "numTiles" : 5 },"k":"iconset8"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"702518_1_A","visible":true,"groups" : [ ] ,"favoredId":-1,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":2,"smoke":3,"favored":3,"trigger":2,"manual":3,"sun":2,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":2,"time":3,"dust":2,"wind":3,"states":[{"cfgKey":"setWindAuto","cfgId":111,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":1},{"cfgKey":"setRainAuto","cfgId":109,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":1}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147483417,"messages":[],"hasErrors":0,"autos":[6,2,1,0,3,4,5]},{"did":10001,"name":"Küche","description":" ","initialized":1,"position":100,"productName":"Troll Comfort DuoFern","serial":"70 24 B1","statusesMap":{"Position":100,"Manuellbetrieb":0},"status_changed":1484417262,"deviceGroup":2,"iconSet":{"name":"Rollladen 1","description":"Rollladen Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen1.png", "numTiles" : 5 },"k":"iconset8"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"7024B1_1_A","visible":true,"groups" : [ 5001 ] ,"favoredId":-1,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":2,"smoke":3,"favored":3,"trigger":2,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":2,"time":3,"dust":2,"wind":3,"states":[{"cfgKey":"setWindAuto","cfgId":111,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":1},{"cfgKey":"setRainAuto","cfgId":109,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":1}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147483403,"messages":[],"hasErrors":0,"autos":[6,2,1,0,3,4,5]},{"did":10005,"name":"Markise","description":" ","initialized":1,"position":0,"productName":"Rohrmotoraktor Umweltsensor","serial":"69 0B C2","statusesMap":{"Position":0,"Manuellbetrieb":0},"status_changed":1483609252,"deviceGroup":2,"iconSet":{"name":"Markise","description":"Markise Icon-Set","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/markise1.png", "numTiles" : 5 },"k":"iconset7"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"690BC2_1_A","visible":true,"groups" : [ ] ,"favoredId":-1,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":3,"smoke":3,"favored":3,"trigger":2,"manual":3,"sun":1,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":2,"dust":3,"wind":3,"states":[{"cfgKey":"setWindAuto","cfgId":111,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":0},{"cfgKey":"setSunAuto","cfgId":105,"state":0},{"cfgKey":"setRainAuto","cfgId":109,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":0}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147483495,"messages":[],"hasErrors":0,"autos":[6,2,1,0,3,4,5]},{"did":10000,"name":"Terrassentür","description":" ","initialized":1,"position":100,"productName":"RolloTron Standard","serial":"40 78 E3","statusesMap":{"Position":100,"Manuellbetrieb":0},"status_changed":1484404126,"deviceGroup":2,"iconSet":{"name":"Rollladen 2","description":"Rollladen Icon-Set mit Streben","strMin":"Auf","strMax":"Zu","valMax":100,"valMin":0,"sprite":{ "imageUri" : "images/sets/rollladen2.png", "numTiles" : 5 },"k":"iconset15"},"iconSetInverted":0,"paired":0,"statusValid":true,"uid":"4078E3_1","visible":true,"groups" : [ 5000, 5001 ] ,"favoredId":-1,"properties":{"rain":3,"smartphone":3,"motion":3,"dusk":2,"smoke":3,"favored":3,"trigger":2,"manual":3,"sun":3,"generic":3,"closingContact":3,"temperature":3,"temperator":3,"warning":3,"dawn":3,"time":2,"dust":2,"wind":3,"states":[{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setTimeAuto","cfgId":101,"state":1},{"cfgKey":"setEveningAuto","cfgId":107,"state":1},{"cfgKey":"setSunAuto","cfgId":105,"state":1},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setAutomationOverall","cfgId":99,"state":0},{"cfgKey":"null","cfgId":0,"state":0},{"cfgKey":"setMorningAuto","cfgId":103,"state":1}]},"sortId":0,"sTypes":[],"version":"1.0","sync":-2147483381,"messages":[],"hasErrors":0,"autos":[2,1,0,3,4]}] }

**Comment by thecleaner82** [comment]
And by the way: I am able to use the RolloTron but not able to change the name or room. I can access the settings but when I hit "fertig" in HomeKit nothing happens and the changes are not saved. 

Greetings

**Comment by jortgies** [comment]
I just published an update which should include the other blinds.

Renaming and changing rooms is working for me, are there any error messages logged?

**Comment by thecleaner82** [comment]
i uninstalled and reinstalled the package but now homebridge is not starting (see below) Do i need to change also the config.jason different to the old package?

[1/15/2017, 11:26:23 AM] [RademacherBlinds] Initializing RademacherBlinds platform...
RademacherBlinds init
[1/15/2017, 11:26:23 AM] Loading 0 accessories...
[1/15/2017, 11:26:23 AM] [RademacherBlinds] Online:   [70 24 16]
[1/15/2017, 11:26:23 AM] [RademacherBlinds] Found:  [70 25 18]
/usr/lib/node_modules/homebridge/lib/platformAccessory.js:15
  if (!displayName) throw new Error("Accessories must be created with a non-empty displayName.");
                    ^

Error: Accessories must be created with a non-empty displayName.
    at new PlatformAccessory (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:15:27)
    at RademacherBlinds.addAccessory (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:62:21)
    at /usr/lib/node_modules/homebridge-rademacher-blinds/index.js:42:34
    at Array.forEach (native)
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-blinds/index.js:35:30)
    at Request.self.callback (/usr/lib/node_modules/homebridge-rademacher-blinds/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-blinds/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)

**Comment by jortgies** [comment]
@thecleaner82 this should be fixed in the latest update.

**Comment by thecleaner82** [comment]
Great, thank you very much it works now. Only the "DuoFern Umweltsensor 9475" that also pilots my sun roof is missing.
