### ISSUE TITLE
Start2smart gateway

### ISSUE THREAD

**Issue by bojomojo** [jortgies/homebridge-rademacher-blinds#11]
Would that also work with the start2smart rademacher gateways?

**Comment by jortgies** [comment]
If the start2smart exposes the same API it would work. I would be willing to add support for the start2smart gateway, please check if your gateway exposes some kind of API.

The Homepilot v5 has endpoints like
`/v4/devices?devtype=Actuator`
`/v4/devices/{deviceID}`

**Comment by bojomojo** [comment]
I just heard on the -homepilot github that it does work. Will test ir out

Sent from my iPhone

On 4. Nov 2020, at 12:05, Jan-Eric Ortgies <notifications@github.com> wrote:

﻿

If the start2smart exposes the same API it would work. I would be willing to add support for the start2smart gateway, please check if your gateway exposes some kind of API.

The Homepilot v5 has endpoints like
/v4/devices?devtype=Actuator
/v4/devices/{deviceID}

**Comment by jortgies** [comment]
From https://github.com/bombadiltom/homebridge-rademacher-homepilot/issues/62

> Confirmed working.
> Exactly same steps as the homepilot.

Will be closing this issue, feel free to reopen if there are any problems.
