### ISSUE TITLE
Shall i install -blinds or -homepilot plugin

### ISSUE THREAD

**Issue by bojomojo** [jortgies/homebridge-rademacher-blinds#12]
Which plugin? -homepilot or -blind?

**Comment by jortgies** [comment]
This depends on what you need. My plugin only has support for the blinds functionality of the Rademacher Homepilot.

If you are using other sensors from Rademacher you are probably better off using the [homebridge-rademacher-homepilot](https://github.com/bombadiltom/homebridge-rademacher-homepilot) plugin, as it adds support for more than just blinds.

**Comment by bojomojo** [comment]
But for blinds, its the same as the homepilot plugin? Or adds anything extra?

Sent from my iPhone

On 7. Nov 2020, at 13:46, Jan-Eric Ortgies <notifications@github.com> wrote:

﻿

This depends on what you need. My plugin only has support for the blinds functionality of the Rademacher Homepilot.

If you are using other sensors from Rademacher you are probably better off using the homebridge-rademacher-homepilot<https://github.com/bombadiltom/homebridge-rademacher-homepilot> plugin, as it adds support for more than just blinds.

**Comment by jortgies** [comment]
Yes, it is mostly the same. The -homepilot plugin was forked some time ago so there may be some changes I am unaware of.
