### ISSUE TITLE
Configuration unclear

### ISSUE THREAD

**Issue by abravion** [jortgies/homebridge-rademacher-blinds#3]
Hi jortgies,

first of all - cool thing that you made a home bridge plugin for the radermacher blinds. i'm not really sure if i am missing something here or there is a problem with the plugin. after installing the plugin and starting homebrdge it shows 

`[2017-3-1 23:17:38] Loaded plugin: homebridge-rademacher-blinds
[2017-3-1 23:17:38] Registering platform 'homebridge-rademacher-blinds.RademacherBlinds'
[2017-3-1 23:17:38] ---
[2017-3-1 23:17:38] Loaded config.json with 0 accessories and 1 platforms.
[2017-3-1 23:17:38] ---
[2017-3-1 23:17:38] Loading 1 platforms...
[2017-3-1 23:17:38] [RademacherBlinds] Initializing RademacherBlinds platform...
[2017-3-1 23:17:38] Loading 0 accessories...
`

but there is nothing shown in the home kit app....i did change the ip adress to match it with my home pilot but it shows me no device... what am i doing wrong?? do i need to put the device id s into the url?

`{
  "bridge" : {
    "name" : "Homebridge",
    "username" : "CC:22:3D:E3:CE:30",
    "port" : 51826,
    "pin" : "031-45-154"
  },
  "accessories" : [],
  "platforms" : [
    {
      "platform" : "RademacherBlinds",
      "name" : "RademacherBlinds",
      "url" : "http://10.1.0.124/deviceajax.do"
    }
  ]
}`

regards phil

**Comment by abravion** [comment]
i see .. you are only searching for 

`                    if(data.productName.includes("RolloTron") || data.productName.includes("Troll Comfort"))
`

but there are much more! 

"Rohrmotor"

should be the most common one...

i am not sure how they are controlled: 
"Heizkörperstellantrieb"
"Schaltaktor 2-Kanal"
"Dimmer"
"Repeater mit Schaltfunktion"
"SX5 DuoFern" (Garage)

would be very cool if we can figure out how to control the rest of the system 👍

**Comment by jortgies** [comment]
I only have access to the Rademacher RolloTron, so unfortunately I can't test any other devices.

Feel free to test your devices and write a pull request.

**Comment by Tarsonion** [comment]
How can i bind the other devices in homebridge? i use the "Rollladenaktor"....

Must i only change the productName in the index? where can i find it?

i need help :)

**Comment by jortgies** [comment]
@Tarsonion the detection is done [here](https://github.com/jortgies/homebridge-rademacher-blinds/blob/master/index.js#L36)

you could include the Rollladenaktor like this:
`if(data.productName.includes("RolloTron") || data.productName.includes("Troll Comfort") || data.productName.includes("Rollladenaktor"))`

(I am not including those devices on purpose, as I can't test them...)
