### ISSUE TITLE
update to homepilot v5

### ISSUE THREAD

**Issue by jortgies** [jortgies/homebridge-rademacher-blinds#9]
this project currently only works with the old homepilot v4 api, updating to homepilot v5 is breaking stuff as the endpoints changed

see also PR #6 which implements a working version using the new homepilot v5 endpoints

**Comment by flobernd** [comment]
Hi there, I'm planning to buy smart blinds from Rademacher and would like to know if the PR is going to be merged anytime soon?

**Comment by jortgies** [comment]
> @jortgies Hi there, I'm planning to buy smart blinds from Rademacher and would like to know if the PR is going to be merged anytime soon?

I have not yet fully reviewed all changes in this PR, but I'm probably not going to merge it because it contains additional features/changes I don't need for the blinds functionality (i.e. Rauchwarnmelder, Universaldimmer, environment sensor)

Feel free to check out the fork which has some more features than just the blinds and has a working v5 API implementation: https://github.com/bombadiltom/homebridge-rademacher-homepilot

**Comment by flobernd** [comment]
Alright, thanks for the answer!
